<?php

/**
 * Implements hook_form_alter().
 *
 * Handy for easily inspecting forms as they're built.
 */
function toolkit_form_alter(&$form, &$form_state, $form_id) {
  $forms = array(

  );

  if (in_array($form_id, $forms)) {
    if (function_exists('ddl')) {
      ddl(array(
        'form' => $form,
        'form_state' => $form_state,
      ), $form_id);
    }
  }
}

/**
 * Implements hook_admin_menu_output_build().
 */
function toolkit_admin_menu_output_build(&$content) {
  dpm($content);
}

/**
 * Return the reference count of a variable.
 * 
 * Returns 0 if a variable has no reference other than itself or doesn't
 * exist.
 *
 * @see http://www.php.net/manual/en/function.debug-zval-dump.php#109146
 */
function refcount(&$var) {
  ob_start();
  debug_zval_dump(array(&$var));
  return preg_replace("/^.+?refcount\((\d+)\).+$/ms", '$1', substr(ob_get_clean(), 24), 1) - 4;
}

/**
 * Return whether a and b reference the same memory
 *
 * @see http://www.php.net/manual/en/function.debug-zval-dump.php#109146
*/
function reference(&$a, &$b) {
    $d = refcount($b);
    $e = &$a;
    return refcount($b) != $d;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * General hook for altering the node base form.
 */
//function toolkit_form_node_form_alter(&$form, &$form_state, $form_id) {
//  dpm(func_get_args(), __FUNCTION__);
//}
