<?php

/**
 * Implements hook_form_alter().
 *
 * Handy for easily inspecting forms as they're built.
 */
function toolkit_form_alter(&$form, &$form_state, $form_id) {
  $forms = array(

  );

  if (in_array($form_id, $forms)) {
    if (function_exists('ddl')) {
      ddl(array(
        'form' => $form,
        'form_state' => $form_state,
      ), $form_id);
    }
  }
}

/**
 * Implements hook_admin_menu_output_build().
 */
function toolkit_admin_menu_output_build(&$content) {
  dpm($content);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * General hook for altering the node base form.
 */
//function toolkit_form_node_form_alter(&$form, &$form_state, $form_id) {
//  dpm(func_get_args(), __FUNCTION__);
//}
